version: "3.8"
services:
  node_frontend:
    restart: always
    container_name: nginx-node
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: nginx-node:v1.0
    ports:
      - "80:80"
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      timeout: 10s
      start_period: 20s
      retries: 5
    depends_on:
      - app
    networks:
      - backnet

  app:
    restart: always
    container_name: backend-app
    build:
      context: ./lib_catalog/
      dockerfile: Dockerfile
    image: my_backend:v1.0
    ports:
      - "8000:8000"
    healthcheck:
      test: curl -sS http://localhost:8000/admin/ || exit 1
      interval: 60s
      timeout: 10s
      start_period: 20s
      retries: 5
    depends_on:
      - postgres_db
    networks:
      - frontnet
      - backnet
  
  postgres_db:
    restart: always
    image: "postgres:13"
    container_name: postgres_db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_NAME
    expose: 
      - "5432"
    networks:
      - backnet


networks:
   frontnet:
      driver: bridge
      ipam: 
        config:
           - subnet: 192.168.88.0/24
             gateway: 192.168.88.1
   backnet:
      driver: bridge
      ipam:
        config:
           - subnet: 192.168.98.0/24
             gateway: 192.168.98.1
